spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  data:
    redis:
      url: ${SPRING_REDIS_URL}
      ssl:
        enabled: true
      timeout: 3000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
        shutdown-timeout: 200ms